// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJr6l_7XSMDW9qgs8FeMNDk__WLffEaNc',
    appId: '1:759328820352:web:97d07f24ad17c91c34ea65',
    messagingSenderId: '759328820352',
    projectId: 'super-app-6cfcc',
    authDomain: 'super-app-6cfcc.firebaseapp.com',
    storageBucket: 'super-app-6cfcc.firebasestorage.app',
    measurementId: 'G-2V9TB4TZ89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_sWbHm2LNWcDj48lFZOLRGJdxaW8IDm4',
    appId: '1:759328820352:android:31a85188d5f8b6bc34ea65',
    messagingSenderId: '759328820352',
    projectId: 'super-app-6cfcc',
    storageBucket: 'super-app-6cfcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepgvoIJ4wys29C2hhE4MZKwjNjwh-6go',
    appId: '1:759328820352:ios:075b99b3980494f734ea65',
    messagingSenderId: '759328820352',
    projectId: 'super-app-6cfcc',
    storageBucket: 'super-app-6cfcc.firebasestorage.app',
    iosBundleId: 'com.example.superApp',
  );
}
